# Generated by Django 4.2.27 on 2026-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=20, null=True),
        ),
    ]
